---
jobs:
  - name: start-job
    serial: true
    plan:
      - get: bosh-src
        trigger: false

  - name: build-ubuntu-trusty
    plan:
      - get: bosh-src
        passed:
          - start-job
      - get: ubuntu-trusty-os-image-version
        params: {bump: minor}
      - task: build
        file: bosh-src/ci/pipelines/os-images-new/tasks/build.yml
        privileged: true
        config:
          params:
            OPERATING_SYSTEM_NAME:      ubuntu
            OPERATING_SYSTEM_VERSION:   trusty
      - put: ubuntu-trusty-os-image-version
        params: {file: ubuntu-trusty-os-image-version/number}
      - put: ubuntu-trusty-os-image
        params:
          file: ubuntu-trusty-os-image.tgz

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: {{branch}}

  - name: ubuntu-trusty-os-image-version
    type: semver
    source:
      driver: s3
      key: os-image-version-key
      bucket: {{bucket}}
      access_key_id: {{aws_access_key}}
      secret_access_key: {{aws_secret_key}}

  - name: ubuntu-trusty-os-image
    type: s3
    source:
      bucket: {{bucket}}
      access_key_id: {{aws_access_key}}
      secret_access_key: {{aws_secret_key}}
